"""Initial seed data — mirrors the original frontend/src/data/products.js content.
This runs only on first startup if the corresponding collections are empty."""

INITIAL_REVIEWS = [
    {"id": "rev-1", "name": "جعفر", "rating": 5,
     "text": "والله قبل التعامل المحترم والاسلوب المتناسق المتجر مره محترف ومضمون مضمون مضمون دفعت فلوسي وانا مغمض الله يكثر من امثالك وبدل المتجر تفتح الف متجر 🙏",
     "order": 0},
    {"id": "rev-2", "name": "زيد", "rating": 5,
     "text": "ما شاء الله والله تعامل ممتاز الله يباركلك ب المتجر واشكرك 🔥",
     "order": 1},
    {"id": "rev-3", "name": "محمود", "rating": 5,
     "text": "ما شاء الله عليك قمة في الاحترام و التعامل 💯",
     "order": 2},
    {"id": "rev-4", "name": "مسعود", "rating": 5,
     "text": "والله سرعة كبيره في التسليم ومضمون الله يرزقكم و اشكركم 🎮",
     "order": 3},
]

INITIAL_FAQS = [
    {"id": "delivery", "icon": "truck",
     "q": "كيف يتم تسليم الطلب؟",
     "a": "يتم تسليم طلبك بشكل فوري وسلس عبر مسح رمز الاستجابة السريعة (QR Code)، لتتمكن من تفعيل ألعابك واشتراكاتك مباشرة وبدون أي تعقيدات.",
     "order": 0},
    {"id": "payment", "icon": "credit-card",
     "q": "ما هي طرق الدفع المتاحة؟",
     "a": "نوفر لك طرق دفع آمنة ومريحة تشمل البطاقات الائتمانية (فيزا وماستركارد)، بالإضافة إلى خدمة (Apple Pay) لتجربة شراء سريعة وموثوقة.",
     "order": 1},
    {"id": "warranty", "icon": "shield-check",
     "q": "هل الألعاب أصلية ومضمونة؟",
     "a": "بكل تأكيد! جميع الألعاب والاشتراكات لدينا أصلية 100%، ومرفقة بـ \"الضمان الذهبي\" الذي يضمن لك حقك وتجربة لعب مستقرة وآمنة تماماً.",
     "order": 2},
]

INITIAL_STORE = {
    "name": "دُكانك",
    "name_en": "Dukkank",
    "tagline": "اشتراكات وألعاب رقمية بأفضل الأسعار",
    "tagline_en": "Digital subscriptions & games at the best prices",
    "whatsapp": "962775585112",
    "whatsappDisplay": "0775585112",
    "instagram": "https://www.instagram.com/dukkank15/",
}

# ---------------------------------------------------------------------------
# All static page copy — every string the customer sees on the homepage
# can be edited from the admin "محتوى الموقع" tab. Keep keys flat-ish so the
# admin UI can render a logical tree.
# ---------------------------------------------------------------------------
INITIAL_CONTENT = {
    "hero": {
        "badge": "متجر موثوق • تسليم فوري",
        "titleLine1": "كل ألعابك واشتراكاتك",
        "titleLine2": "بضغطة زر.",
        "subtitle": "اشتراكات PlayStation Plus وألعاب رقمية أصلية بأفضل الأسعار، مع تسليم فوري ودعم مباشر على واتساب.",
        "ctaBrowse": "تصفّح المنتجات",
        "ctaWhatsApp": "راسلنا على واتساب",
        "benefitInstant": "تسليم فوري",
        "benefitOriginal": "حسابات أصلية",
        "benefitSupport": "دعم مباشر",
    },
    "essential": {
        "eyebrow": "الاشتراكات",
        "title": "بلايستيشن بلس أساسي",
        "description": "للاعب اللي بدو الأساسيات: ألعاب شهرية، أونلاين متعدد اللاعبين.",
        "featureTitle": "ليش الاشتراك الأساسي؟",
        "featureBullets": [
            "اللعب أونلاين مع أصدقائك",
            "ألعاب شهرية مجانية",
        ],
    },
    "extra": {
        "eyebrow": "الاشتراكات",
        "title": "بلايستيشن بلس إضافي",
        "description": "مكتبة أوسع تتجاوز ٤٠٠ لعبة من Sony وشركاء آخرين، بسعر يستاهل.",
        "featureTitle": "ليش الاشتراك الإضافي؟",
        "featureBullets": [
            "مكتبة ضخمة (+400 لعبة)",
            "تجارب لعب مجانية لألعاب مختارة",
            "كل ميزات الأساسي",
        ],
    },
    "comparison": {
        "eyebrow": "مقارنة الباقات",
        "title": "أساسي ولا إضافي؟ شو الفرق؟",
        "description": "كل خطة لها نقاط قوتها — هاي مقارنة سريعة عشان تختار صح من أول مرة.",
        "popularBadge": "الأكثر طلباً",
        "essentialColLabel": "أساسي",
        "extraColLabel": "إضافي",
        "ctaStart": "جاهز تبدأ؟",
        "ctaEssential": "اختر الأساسي",
        "ctaExtra": "اختر الإضافي",
        "rows": [
            {"feature": "اللعب أونلاين متعدد اللاعبين", "essential": True, "extra": True},
            {"feature": "ألعاب شهرية مجانية", "essential": True, "extra": True},
            {"feature": "خصومات في المتجر", "essential": True, "extra": True},
            {"feature": "تخزين سحابي للحفظ", "essential": True, "extra": True},
            {"feature": "مكتبة +400 لعبة", "essential": False, "extra": True},
            {"feature": "تجارب لعب مجانية مختارة", "essential": False, "extra": True},
        ],
    },
    "bundles": {
        "eyebrow": "باقات مدمجة",
        "title": "خذ اشتراك + لعبة بسعر أقل",
        "description": "وفّر أكثر مع باقاتنا الجاهزة — اشتراك مع لعبتك المفضّلة بسعر مدمج.",
    },
    "bundleBuilder": {
        "eyebrow": "ابني باقتك",
        "title": "اختار أنت، واحنا نخصملك",
        "description": "ضمّ اشتراك + ألعاب، وكل ما زدت عنصر زاد الخصم تلقائياً.",
        "discountsLabel": "نسب الخصم حسب الاشتراك والمدة",
        "step1": "١) اختر جهازك",
        "step1Hint": "السعر يتغير حسب الجهاز",
        "step2": "٢) أضف اشتراك (اختياري)",
        "step3": "٣) أضف ألعاب",
        "summaryTitle": "ملخص باقتك",
        "summaryEmpty": "لسه ما اخترت شي. ابدأ بإضافة اشتراك أو لعبة.",
        "subtotal": "المجموع الفرعي",
        "discountLabel": "خصم باقتك",
        "totalLabel": "المجموع",
        "hintNoSub": "💡 أضف اشتراك للحصول على خصم على كامل الباقة!",
        "addAll": "أضف باقتك للسلة",
        "addedAll": "أُضيفت!",
        "reset": "ابدأ من جديد",
    },
    "games": {
        "eyebrow": "ألعاب رقمية",
        "title": "أبرز الألعاب المتاحة",
        "description": "اضغط على أي لعبة لرؤية تفاصيلها الكاملة — تريلر، مواصفات، وألعاب مشابهة.",
        "customGameTitle": "لعبة محددة بدّك إياها وما لقيتها هون؟",
        "customGameSubtitle": "احكينا على واتساب وراح نأمنّها لك بأفضل سعر.",
        "customGameCta": "اطلب لعبة مخصصة",
    },
    "reviews": {
        "eyebrow": "آراء العملاء",
        "title": "ثقة عملائنا أهم شي عنا.",
        "description": "عملاء جربوا دُكانك. هاي شهاداتهم.",
        "ratingOutOf5": "من 5 نجوم",
        "basedOn": "مبني على",
    },
    "faq": {
        "badge": "الأسئلة الشائعة",
        "title": "أي استفسار عندك؟",
        "description": "إذا لقيت إجابة هنا، رائع! وإذا لا، فريقنا متواجد ٢٤/٧ على واتساب لمساعدتك.",
    },
    "emailSignup": {
        "eyebrow": "اشترك بنشرتنا",
        "title": "احصل على خصم 10% فوراً 🎁",
        "description": "سجّل إيميلك الآن واستلم كوبون خصم شخصي ينطبق على أول طلب لك.",
        "placeholder": "your-email@example.com",
        "cta": "احصل على الكوبون",
        "success": "تم! نسخت الكوبون لك — استخدمه في الواتساب وقت الطلب.",
    },
    "footer": {
        "tagline": "متجرك الموثوق للاشتراكات والألعاب الرقمية.",
        "linksTitle": "روابط سريعة",
        "contactTitle": "تواصل معنا",
        "copyright": "© دُكانك — كل الحقوق محفوظة.",
    },
}

INITIAL_SUBSCRIPTIONS = [
    {
        "id": "essential",
        "name": "اشتراك أساسي",
        "name_en": "Essential",
        "tagline": "خطط ألعاب أساسية بسعر مميز",
        "tagline_en": "Core gaming plans at a great price",
        "accent": "blue",
        "durations": [
            {"id": "ess-1m",  "label": "شهر واحد", "label_en": "1 Month",  "four": 6.5, "five": None, "bundleDiscountPct": 5},
            {"id": "ess-3m",  "label": "٣ شهور",   "label_en": "3 Months", "four": 12,  "five": 19,   "bundleDiscountPct": 8},
            {"id": "ess-12m", "label": "سنة كاملة","label_en": "12 Months","four": 24,  "five": 48,   "bundleDiscountPct": 12},
        ],
    },
    {
        "id": "extra",
        "name": "اشتراك إضافي",
        "name_en": "Extra",
        "tagline": "تجربة أوسع مع مكتبة ألعاب أكبر",
        "tagline_en": "A broader library and richer experience",
        "accent": "red",
        "durations": [
            {"id": "ext-1m",  "label": "شهر واحد", "label_en": "1 Month",  "four": 9,  "five": None, "bundleDiscountPct": 7},
            {"id": "ext-3m",  "label": "٣ شهور",   "label_en": "3 Months", "four": 19, "five": 28,   "bundleDiscountPct": 10},
            {"id": "ext-12m", "label": "سنة كاملة","label_en": "12 Months","four": 42, "five": 59,   "bundleDiscountPct": 15},
        ],
    },
]

INITIAL_GAMES = [
    {"id": "eafc26", "name": "EA Sports FC 26", "sub": "Football • Career & Ultimate Team",
     "image": "/games/eafc26.jpg", "gradientFrom": "#1c5e3a", "gradientTo": "#0f2e1c",
     "four": 16, "five": 26, "available": True, "bestSeller": True},
    {"id": "blackops7", "name": "Call of Duty: Black Ops 7", "sub": "FPS • Multiplayer & Zombies",
     "image": "/games/blackops7.jpg", "gradientFrom": "#2a2f1a", "gradientTo": "#0d0f08",
     "four": 20, "five": 36, "available": True, "bestSeller": True},
    {"id": "blackops6", "name": "Call of Duty: Black Ops 6", "sub": "FPS • Campaign, MP, Zombies",
     "image": "/games/blackops6.jpg", "gradientFrom": "#1f2310", "gradientTo": "#080a04",
     "four": 18, "five": 23, "available": True, "bestSeller": False},
    {"id": "battlefield6", "name": "Battlefield 6", "sub": "Large-scale war shooter",
     "image": "/games/bf6.jpg", "gradientFrom": "#3d2a14", "gradientTo": "#160e05",
     "four": None, "five": 36, "available": True, "bestSeller": False},
    {"id": "re9", "name": "Resident Evil Requiem", "sub": "Survival horror",
     "image": "/games/re9.jpg", "gradientFrom": "#4a0e0e", "gradientTo": "#1a0303",
     "four": None, "five": 36, "available": True, "bestSeller": False},
    {"id": "wwe26", "name": "WWE 2K26", "sub": "Wrestling • Top superstars",
     "image": "/games/wwe26.jpg", "gradientFrom": "#3a1a1a", "gradientTo": "#0e0405",
     "four": None, "five": 42, "available": True, "bestSeller": False},
    {"id": "gta5", "name": "Grand Theft Auto V", "sub": "Open world • Action",
     "image": "/games/gta5.jpg", "gradientFrom": "#13343f", "gradientTo": "#04141a",
     "four": 17, "five": 18, "available": True, "bestSeller": True},
    {"id": "rdr2", "name": "Red Dead Redemption 2", "sub": "Western adventure epic",
     "image": "/games/rdr2.jpg", "gradientFrom": "#4a2412", "gradientTo": "#180a04",
     "four": 17, "five": 19, "available": True, "bestSeller": True},
    {"id": "spiderman2", "name": "Marvel's Spider-Man 2 (Arabic Dub)", "sub": "Action • Arabic Dubbed",
     "image": "/games/spiderman2.jpg", "gradientFrom": "#5a0a0a", "gradientTo": "#1d0306",
     "four": None, "five": 37, "available": True, "bestSeller": False},
    {"id": "forza5", "name": "Forza Horizon 5", "sub": "Open-world racing",
     "image": "/games/forza5.jpg", "gradientFrom": "#0d3a4a", "gradientTo": "#031018",
     "four": None, "five": 32, "available": True, "bestSeller": False},
    {"id": "arc-raiders", "name": "Arc Raiders", "sub": "Sci-fi extraction shooter",
     "image": "/games/arc-raiders.jpg", "gradientFrom": "#2a3340", "gradientTo": "#0a0e14",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "ghost-tsushima", "name": "Ghost of Tsushima (Arabic)", "sub": "Samurai open-world • Arabic Dubbed",
     "image": "/games/ghost-tsushima.jpg", "gradientFrom": "#5a1010", "gradientTo": "#1a0405",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "ghost-yotei", "name": "Ghost of Yotei", "sub": "Samurai action-adventure",
     "image": "/games/ghost-yotei.jpg", "gradientFrom": "#3a0d0d", "gradientTo": "#120303",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "ready-or-not", "name": "Ready or Not", "sub": "Tactical SWAT shooter",
     "image": "/games/ready-or-not.jpg", "gradientFrom": "#1a1a1a", "gradientTo": "#050505",
     "four": None, "five": 30, "available": True, "bestSeller": False},
    {"id": "tlou2", "name": "The Last of Us Part II", "sub": "Story-driven survival action",
     "image": "/games/tlou2.jpg", "gradientFrom": "#2c2415", "gradientTo": "#0c0a05",
     "four": 19, "five": 26, "available": True, "bestSeller": False},
    {"id": "tlou1", "name": "The Last of Us Part I — Remastered", "sub": "Story-driven survival epic",
     "image": "/games/tlou1.jpg", "gradientFrom": "#1d2a18", "gradientTo": "#070a05",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "crew-motorfest", "name": "The Crew Motorfest", "sub": "Open-world racing playground",
     "image": "/games/crew-motorfest.jpg", "gradientFrom": "#1a4f7a", "gradientTo": "#04161f",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "elden-ring", "name": "Elden Ring", "sub": "Dark fantasy souls-like",
     "image": "/games/elden-ring.jpg", "gradientFrom": "#3a2710", "gradientTo": "#100905",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "re8", "name": "Resident Evil 8: Village", "sub": "Survival horror",
     "image": "/games/re8.jpg", "gradientFrom": "#2a1010", "gradientTo": "#0a0202",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "re7", "name": "Resident Evil 7: Biohazard", "sub": "First-person survival horror",
     "image": "/games/re7.jpg", "gradientFrom": "#1e1a1a", "gradientTo": "#080606",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "nba2k26", "name": "NBA 2K26 Slam Edition", "sub": "Basketball simulation",
     "image": "/games/nba2k26.webp", "gradientFrom": "#3a1a05", "gradientTo": "#120602",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "horizon-fw", "name": "Horizon Forbidden West", "sub": "Action RPG • Post-apocalyptic",
     "image": "/games/horizon-fw.jpg", "gradientFrom": "#1c4a5e", "gradientTo": "#05161e",
     "four": None, "five": None, "available": True, "bestSeller": False},
]

INITIAL_BUNDLES = [
    {"id": "bundle-extra12-fc26", "subId": "extra", "durationId": "ext-12m", "gameId": "eafc26",
     "tier": "five", "bundlePrice": 75, "available": True},
    {"id": "bundle-ess12-blackops7", "subId": "essential", "durationId": "ess-12m", "gameId": "blackops7",
     "tier": "five", "bundlePrice": 75, "available": True},
    {"id": "bundle-extra3-gta5", "subId": "extra", "durationId": "ext-3m", "gameId": "gta5",
     "tier": "five", "bundlePrice": 40, "available": True},
    {"id": "bundle-extra12-rdr2", "subId": "extra", "durationId": "ext-12m", "gameId": "rdr2",
     "tier": "five", "bundlePrice": 70, "available": True},
]
