"""Initial seed data — mirrors the original frontend/src/data/products.js content.
This runs only on first startup if the corresponding collections are empty."""

INITIAL_STORE = {
    "name": "دُكانك",
    "name_en": "Dukkank",
    "tagline": "اشتراكات وألعاب رقمية بأفضل الأسعار",
    "tagline_en": "Digital subscriptions & games at the best prices",
    "whatsapp": "962775585112",
    "whatsappDisplay": "0775585112",
    "instagram": "https://www.instagram.com/dukkank15/",
}

INITIAL_SUBSCRIPTIONS = [
    {
        "id": "essential",
        "name": "اشتراك أساسي",
        "name_en": "Essential",
        "tagline": "خطط ألعاب أساسية بسعر مميز",
        "tagline_en": "Core gaming plans at a great price",
        "accent": "blue",
        "durations": [
            {"id": "ess-1m",  "label": "شهر واحد", "label_en": "1 Month",  "four": 6.5, "five": None},
            {"id": "ess-3m",  "label": "٣ شهور",   "label_en": "3 Months", "four": 12,  "five": 19},
            {"id": "ess-12m", "label": "سنة كاملة","label_en": "12 Months","four": 24,  "five": 48},
        ],
    },
    {
        "id": "extra",
        "name": "اشتراك إضافي",
        "name_en": "Extra",
        "tagline": "تجربة أوسع مع مكتبة ألعاب أكبر",
        "tagline_en": "A broader library and richer experience",
        "accent": "red",
        "durations": [
            {"id": "ext-1m",  "label": "شهر واحد", "label_en": "1 Month",  "four": 9,  "five": None},
            {"id": "ext-3m",  "label": "٣ شهور",   "label_en": "3 Months", "four": 19, "five": 28},
            {"id": "ext-12m", "label": "سنة كاملة","label_en": "12 Months","four": 42, "five": 59},
        ],
    },
]

INITIAL_GAMES = [
    {"id": "eafc26", "name": "EA Sports FC 26", "sub": "Football • Career & Ultimate Team",
     "image": "/games/eafc26.jpg", "gradientFrom": "#1c5e3a", "gradientTo": "#0f2e1c",
     "four": 16, "five": 26, "available": True, "bestSeller": True},
    {"id": "blackops7", "name": "Call of Duty: Black Ops 7", "sub": "FPS • Multiplayer & Zombies",
     "image": "/games/blackops7.jpg", "gradientFrom": "#2a2f1a", "gradientTo": "#0d0f08",
     "four": 20, "five": 36, "available": True, "bestSeller": True},
    {"id": "blackops6", "name": "Call of Duty: Black Ops 6", "sub": "FPS • Campaign, MP, Zombies",
     "image": "/games/blackops6.jpg", "gradientFrom": "#1f2310", "gradientTo": "#080a04",
     "four": 18, "five": 23, "available": True, "bestSeller": False},
    {"id": "battlefield6", "name": "Battlefield 6", "sub": "Large-scale war shooter",
     "image": "/games/bf6.jpg", "gradientFrom": "#3d2a14", "gradientTo": "#160e05",
     "four": None, "five": 36, "available": True, "bestSeller": False},
    {"id": "re9", "name": "Resident Evil Requiem", "sub": "Survival horror",
     "image": "/games/re9.jpg", "gradientFrom": "#4a0e0e", "gradientTo": "#1a0303",
     "four": None, "five": 36, "available": True, "bestSeller": False},
    {"id": "wwe26", "name": "WWE 2K26", "sub": "Wrestling • Top superstars",
     "image": "/games/wwe26.jpg", "gradientFrom": "#3a1a1a", "gradientTo": "#0e0405",
     "four": None, "five": 42, "available": True, "bestSeller": False},
    {"id": "gta5", "name": "Grand Theft Auto V", "sub": "Open world • Action",
     "image": "/games/gta5.jpg", "gradientFrom": "#13343f", "gradientTo": "#04141a",
     "four": 17, "five": 18, "available": True, "bestSeller": True},
    {"id": "rdr2", "name": "Red Dead Redemption 2", "sub": "Western adventure epic",
     "image": "/games/rdr2.jpg", "gradientFrom": "#4a2412", "gradientTo": "#180a04",
     "four": 17, "five": 19, "available": True, "bestSeller": True},
    {"id": "spiderman2", "name": "Marvel's Spider-Man 2 (Arabic Dub)", "sub": "Action • Arabic Dubbed",
     "image": "/games/spiderman2.jpg", "gradientFrom": "#5a0a0a", "gradientTo": "#1d0306",
     "four": None, "five": 37, "available": True, "bestSeller": False},
    {"id": "forza5", "name": "Forza Horizon 5", "sub": "Open-world racing",
     "image": "/games/forza5.jpg", "gradientFrom": "#0d3a4a", "gradientTo": "#031018",
     "four": None, "five": 32, "available": True, "bestSeller": False},
    {"id": "arc-raiders", "name": "Arc Raiders", "sub": "Sci-fi extraction shooter",
     "image": "/games/arc-raiders.jpg", "gradientFrom": "#2a3340", "gradientTo": "#0a0e14",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "ghost-tsushima", "name": "Ghost of Tsushima (Arabic)", "sub": "Samurai open-world • Arabic Dubbed",
     "image": "/games/ghost-tsushima.jpg", "gradientFrom": "#5a1010", "gradientTo": "#1a0405",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "ghost-yotei", "name": "Ghost of Yotei", "sub": "Samurai action-adventure",
     "image": "/games/ghost-yotei.jpg", "gradientFrom": "#3a0d0d", "gradientTo": "#120303",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "ready-or-not", "name": "Ready or Not", "sub": "Tactical SWAT shooter",
     "image": "/games/ready-or-not.jpg", "gradientFrom": "#1a1a1a", "gradientTo": "#050505",
     "four": None, "five": 30, "available": True, "bestSeller": False},
    {"id": "tlou2", "name": "The Last of Us Part II", "sub": "Story-driven survival action",
     "image": "/games/tlou2.jpg", "gradientFrom": "#2c2415", "gradientTo": "#0c0a05",
     "four": 19, "five": 26, "available": True, "bestSeller": False},
    {"id": "tlou1", "name": "The Last of Us Part I — Remastered", "sub": "Story-driven survival epic",
     "image": "/games/tlou1.jpg", "gradientFrom": "#1d2a18", "gradientTo": "#070a05",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "crew-motorfest", "name": "The Crew Motorfest", "sub": "Open-world racing playground",
     "image": "/games/crew-motorfest.jpg", "gradientFrom": "#1a4f7a", "gradientTo": "#04161f",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "elden-ring", "name": "Elden Ring", "sub": "Dark fantasy souls-like",
     "image": "/games/elden-ring.jpg", "gradientFrom": "#3a2710", "gradientTo": "#100905",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "re8", "name": "Resident Evil 8: Village", "sub": "Survival horror",
     "image": "/games/re8.jpg", "gradientFrom": "#2a1010", "gradientTo": "#0a0202",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "re7", "name": "Resident Evil 7: Biohazard", "sub": "First-person survival horror",
     "image": "/games/re7.jpg", "gradientFrom": "#1e1a1a", "gradientTo": "#080606",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "nba2k26", "name": "NBA 2K26 Slam Edition", "sub": "Basketball simulation",
     "image": "/games/nba2k26.webp", "gradientFrom": "#3a1a05", "gradientTo": "#120602",
     "four": None, "five": None, "available": True, "bestSeller": False},
    {"id": "horizon-fw", "name": "Horizon Forbidden West", "sub": "Action RPG • Post-apocalyptic",
     "image": "/games/horizon-fw.jpg", "gradientFrom": "#1c4a5e", "gradientTo": "#05161e",
     "four": None, "five": None, "available": True, "bestSeller": False},
]

INITIAL_BUNDLES = [
    {"id": "bundle-extra12-fc26", "subId": "extra", "durationId": "ext-12m", "gameId": "eafc26",
     "tier": "five", "bundlePrice": 75, "available": True},
    {"id": "bundle-ess12-blackops7", "subId": "essential", "durationId": "ess-12m", "gameId": "blackops7",
     "tier": "five", "bundlePrice": 75, "available": True},
    {"id": "bundle-extra3-gta5", "subId": "extra", "durationId": "ext-3m", "gameId": "gta5",
     "tier": "five", "bundlePrice": 40, "available": True},
    {"id": "bundle-extra12-rdr2", "subId": "extra", "durationId": "ext-12m", "gameId": "rdr2",
     "tier": "five", "bundlePrice": 70, "available": True},
]
